spring:
  application:
    name: realmysql80
  docker:
    compose:
      lifecycle-management: start_and_stop
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: secret

management:
  endpoints:
    web:
      exposure:
        include: prometheus
